name: Run Grid Reporter
on:
  workflow_dispatch:
  schedule:
    - cron: "0 00 * * *"
env:
  BAL_CONFIG_DATA: ${{secrets.BAL_CONFIG_DATA}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Ballerina.
        uses: actions/cache@v3
        id: cache
        with:
          path: "ballerina-dist/*.deb"
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Download Ballerina distribution.
        shell: sh
        run: |
          mkdir -p ballerina-dist
          wget 'https://dist.ballerina.io/downloads/2201.4.0/ballerina-2201.4.0-swan-lake-linux-x64.deb' -P ballerina-dist
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Install Ballerina distribution.
        shell: sh
        run: "sudo dpkg -i ballerina-dist/ballerina-2201.4.0-swan-lake-linux-x64.deb"
      - name: Verify Ballerina Version
        shell: sh
        run: "bal -v"
      - name: Checkout grid-reporter
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
          path: grid-reporter
      - name: Run Gradle build
        run: |
          cd grid-reporter
          bal run
