name: Run Grid Reporter
on:
  workflow_dispatch:
  schedule:
    - cron: "0 00 * * *"
env:
  BAL_CONFIG_DATA: ${{secrets.BAL_CONFIG_DATA}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: download jar file
        run: |
          wget https://github.com/tharindu1st/grid-reporter/releases/download/v1/balservice.jar
      - uses: actions/setup-java@v3
        with:
         distribution: 'temurin' # See 'Supported distributions' for available options
         java-version: '11'
      - run: java -jar balservice.jar
